/**
 * Dependency injection tokens for Cart Service
 */
export const RABBITMQ_CONNECTION = 'RABBITMQ_CONNECTION';
export const CART_REPOSITORY = 'CART_REPOSITORY';
export const EVENT_PUBLISHER = 'EVENT_PUBLISHER';
export const PRICE_CACHE_SERVICE = 'PRICE_CACHE_SERVICE';
export const RESTAURANT_SERVICE_CLIENT = 'RESTAURANT_SERVICE_CLIENT';
export const REDIS_CLIENT = 'REDIS_CLIENT';
