/**
 * tRPC Definitions Package
 *
 * Shared types for inter-service tRPC communication.
 * Enables type-safe synchronous calls between microservices.
 *
 * The AppRouter type is auto-generated by nestjs-trpc CLI.
 * Run `npx nestjs-trpc generate` to regenerate after router changes.
 */

// Auto-generated AppRouter type for client-side type safety
export type { AppRouter } from './generated/server.js';

// Context interface for tRPC procedure context
export type { CreateTRPCContext, TRPCContext } from './context.js';
